[[plugin.prepend_fetchers]]
id = "git"
url = "*/"
run = "git"

[mgr]
show_hidden = true
sort_by = "mtime"
sort_reverse = true         # newest files first
sort_dir_first = true       # folders before files
linemode = "size_and_mtime" # cf. init.lua
