version = 1

[envs.ruff]
channels = ["conda-forge"]
dependencies = { ruff = "*" }
exposed = { ruff = "ruff" }

[envs.nox]
channels = ["conda-forge"]
dependencies = { nox = "*" }
exposed = { tox-to-nox = "tox-to-nox", nox = "nox" }

[envs.mypy]
channels = ["conda-forge"]
dependencies = { mypy = "*" }
exposed = { dmypy = "dmypy", mypyc = "mypyc", mypy = "mypy", stubtest = "stubtest", stubgen = "stubgen" }

[envs.cookiecutter]
channels = ["conda-forge"]
dependencies = { cookiecutter = "*" }
exposed = { cookiecutter = "cookiecutter" }

[envs.cruft]
channels = ["conda-forge"]
dependencies = { cruft = "*" }
exposed = { cruft = "cruft" }

[envs.pre-commit]
channels = ["conda-forge"]
dependencies = { pre-commit = "*" }
exposed = { pre-commit = "pre-commit" }

[envs.ripgrep]
channels = ["conda-forge"]
dependencies = { ripgrep = "*" }
exposed = { rg = "rg" }

[envs.conda-tree]
channels = ["conda-forge"]
dependencies = { conda-tree = "*" }
exposed = { conda-tree = "conda-tree" }

[envs.rattler-build]
channels = ["conda-forge"]
dependencies = { rattler-build = "*" }
exposed = { rattler-build = "rattler-build" }

[envs.validate-pyproject]
channels = ["conda-forge"]
dependencies = { validate-pyproject = "*" }
exposed = { validate-pyproject = "validate-pyproject" }

[envs.uv]
channels = ["conda-forge"]
dependencies = { uv = "*" }
exposed = { uv = "uv", uvx = "uvx" }

[envs.direnv]
channels = ["conda-forge"]
dependencies = { direnv = "*" }
exposed = { direnv = "direnv" }

[envs.pandoc]
channels = ["conda-forge"]
dependencies = { pandoc = "*", pandoc-crossref = "*" }
exposed = { pandoc = "pandoc", pandoc-lua = "pandoc-lua", pandoc-server = "pandoc-server", pandoc-crossref = "pandoc-crossref" }

[envs.pyflowchart]
channels = ["conda-forge"]
dependencies = { pyflowchart = "*" }

[envs.lazygit]
channels = ["conda-forge"]
dependencies = { lazygit = "*" }
exposed = { lazygit = "lazygit" }

[envs.black]
channels = ["conda-forge"]
dependencies = { black = "*" }
exposed = { black = "black", blackd = "blackd" }

[envs.pynvim]
channels = ["conda-forge"]
dependencies = { pynvim = "*" }
exposed = { pynvim-python = "pynvim-python" }

[envs.ghostscript]
channels = ["conda-forge"]
dependencies = { ghostscript = "*" }
exposed = { gs = "gs", dvipdf = "dvipdf", eps2eps = "eps2eps", gsbj = "gsbj", gsdj = "gsdj", gsdj500 = "gsdj500", gslj = "gslj", gslp = "gslp", gsnd = "gsnd", lprsetup = "lprsetup", pdf2dsc = "pdf2dsc", pdf2ps = "pdf2ps", pf2afm = "pf2afm", pfbtopfa = "pfbtopfa", pphs = "pphs", printafm = "printafm", ps2ascii = "ps2ascii", ps2epsi = "ps2epsi", ps2pdf = "ps2pdf", ps2pdf12 = "ps2pdf12", ps2pdf13 = "ps2pdf13", ps2pdf14 = "ps2pdf14", ps2pdfwr = "ps2pdfwr", ps2ps = "ps2ps", ps2ps2 = "ps2ps2", unix-lpr = "unix-lpr" }
